services:
  - type: web
    name: vouchify-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vouchify_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: vouchify-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: vouchify-db
          property: connectionString 